### ISSUE TITLE
ONNX export does not work for EfficientNet model due to missing operator (AdaptiveAvgPooling2D)

### ISSUE THREAD

**Issue by hfassold** [apache/incubator-mxnet#16200]
I am trying to convert the 'EfficientNet' pre-trained model (B0 variant) to ONNX format.
See paper https://arxiv.org/abs/1905.11946

Unfortunately, this does not work because it seems that one operator is missing.
The error thrown is 'AttributeError: No conversion function registered for op type _contrib_AdaptiveAvgPooling2D yet'

MXNet version: 1.5.0

Code to reproduce this issue:

import numpy as np
import gluoncv2
from gluoncv2.model_provider import get_model as glcv2_get_model
import mxnet as mx
from mxnet.contrib import onnx as onnx_mxnet
effnetb0 = glcv2_get_model("efficientnet_b0", pretrained=True)
input_shape = (1, 3, 224, 224)
x = mx.nd.zeros(input_shape, ctx=mx.cpu())
effnetb0.hybridize()
y = effnetb0(x)
effnetb0.export('effnetb0')
converted_model_path = onnx_mxnet.export_model('effnetb0-symbol.json', 'effnetb0-0000.params', [input_shape], np.float32, 'effnetb0.onnx', verbose = True)

**Comment by TristonC** [comment]
@szha  Has this issue been solved in 1.x?

**Comment by Zha0q1** [comment]
yes, this has been partially resolved. we support the output_size==1 case (equivalent to global pooling). Other cases are not supported due to onnx not having a adaptive avg pooling op. 

you can find the new operator support matrix here https://github.com/apache/incubator-mxnet/tree/v1.x/python/mxnet/onnx#operator-support-matrix. The new onnx support will be released in mxnet 1.9 soon

**Comment by bankholdup** [comment]
Hi!

I'm trying to convert EfficientB0 mxnet model to ncnn, and get the same error:
"_contrib_AdaptiveAvgPooling2D not supported yet!"

I'm using:
mxnet version: 1.5.0
onnx version: 1.10.1
Win10

Could you please with it?
