### ISSUE TITLE
can't run neural art end2end ?

### ISSUE THREAD

**Issue by Zepan** [apache/incubator-mxnet#2501]
I copy end2end/*.py to neural-style folder, fix some path in py, and run boost_train.py, still error like that:

```
zp@ubuntu:~/develop/mxnet/example/neural-style$ python boost_train.py 
Traceback (most recent call last):
  File "boost_train.py", line 23, in <module>
    style_mod = basic.get_style_module("style", dshape, ctx, vgg_params)
  File "/home/zp/develop/mxnet/example/neural-style/basic.py", line 68, in get_style_module
    style, content = vgg.get_vgg_symbol(prefix)
AttributeError: 'module' object has no attribute 'get_vgg_symbol'
```

it seems model_vgg19.py not updated?  how to run end2end?

**Comment by antinucleon** [comment]
sorry for this. The ```vgg``` is https://github.com/dmlc/mxnet/blob/master/example/neural-style/model_vgg19.py

I will make a refactor of code after multi-gpu version is done.

**Comment by antinucleon** [comment]
Sorry yes I forget to commit it. I will commit it soon

**Comment by antinucleon** [comment]
Fixed in https://github.com/dmlc/mxnet/pull/2502

**Comment by Zepan** [comment]
the new model is ok.
but i still don't know how to run the example, it seems need some parmeters?
could you give the example command to run it?
```
zp@ubuntu:~/develop/mxnet/example/neural-style/end_to_end$ python boost_train.py 
Unknown params: target_gram_3, init with 0
Unknown params: target_gram_2, init with 0
Unknown params: target_gram_1, init with 0
Unknown params: target_gram_0, init with 0
Unknown params: target_gram_4, init with 0
Unknown params: target_content, init with 0
Traceback (most recent call last):
  File "boost_train.py", line 34, in <module>
    loss.set_params(extra_args, {}, True, True)
TypeError: set_params() takes exactly 3 arguments (5 given)
```

**Comment by antinucleon** [comment]
The command is correct, I think you need to pull newest mxnet. If your set
params function is different to
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L455

It means you are not using newest mxnet
On Wed, Jun 22, 2016 at 00:27 Zepan <notifications@github.com> wrote:

> the new model is ok.
> but i still don't know how to run the example, it seems need some
> parmeters?
> could you give the example command to run it?
>
> zp@ubuntu:~/develop/mxnet/example/neural-style/end_to_end$ python boost_train.py
> Unknown params: target_gram_3, init with 0
> Unknown params: target_gram_2, init with 0
> Unknown params: target_gram_1, init with 0
> Unknown params: target_gram_0, init with 0
> Unknown params: target_gram_4, init with 0
> Unknown params: target_content, init with 0
> Traceback (most recent call last):
>   File "boost_train.py", line 34, in <module>
>     loss.set_params(extra_args, {}, True, True)
> TypeError: set_params() takes exactly 3 arguments (5 given)
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2501#issuecomment-227664584>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13nEoKQOYYqjsr3G9JNxOSwJPt4Tlks5qOOP9gaJpZM4I7c2I>
> .
>
-- 
Sent from mobile phone

**Comment by Zepan** [comment]
it is same, i had pull it this noon.  maybe there are some hack you forget commit?

**Comment by antinucleon** [comment]
Maybe. Sorry for that I will double check it again tomorrow to make sure
everything is in order.
On Wed, Jun 22, 2016 at 00:39 Zepan <notifications@github.com> wrote:

> it is same, i had pull it this noon. maybe there are some hack you forget
> commit?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2501#issuecomment-227666713>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13oHUFB8ifOLCVyw07HHTZr_B4nBRks5qOOangaJpZM4I7c2I>
> .
>
-- 
Sent from mobile phone

**Comment by randomrandom** [comment]
I also have troubles running the end-to-end algo. I'm new to mxnet, so I'm not sure how to fix it, this is the output:

> MPLBACKEND=Agg USE_CUDNN=0 python boost_inference.py 
libdc1394 error: Failed to initialize libdc1394
[08:09:44] /root/side-projects/test_install/mxnet/dmlc-core/include/dmlc/logging.h:235: [08:09:44] src/operator/./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 1513881600 Bytes
Given: 536870912 Bytes
[08:09:44] /root/side-projects/test_install/mxnet/dmlc-core/include/dmlc/logging.h:235: [08:09:44] src/engine/./threaded_engine.h:306: [08:09:44] src/operator/./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 1513881600 Bytes
Given: 536870912 Bytes
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [08:09:44] src/engine/./threaded_engine.h:306: [08:09:44] src/operator/./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 1513881600 Bytes
Given: 536870912 Bytes
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted

I tried increasing the workspace in the model_vgg19 file to 2048, however this didn't help. Any ideas? Is it possible to use cudnn to get around this problem? How can I run the modell with cudnn?

**Comment by antinucleon** [comment]
The out of memory may caused because your input is too large. Current model
is experimental and I didn't do any optimization on memory. I will do a
refactor in next week.
On Sat, Jun 25, 2016 at 01:26 George Stoyanov <notifications@github.com>
wrote:

> I also have troubles running the end-to-end algo. I'm new to mxnet, so I'm
> not sure how to fix it, this is the output:
>
> MPLBACKEND=Agg USE_CUDNN=0 python boost_inference.py
> libdc1394 error: Failed to initialize libdc1394
> [08:09:44]
> /root/side-projects/test_install/mxnet/dmlc-core/include/dmlc/logging.h:235:
> [08:09:44] src/operator/./convolution-inl.h:279: Check failed:
> (param_.workspace) >= (required_size)
> Minimum workspace size: 1513881600 Bytes
> Given: 536870912 Bytes
> [08:09:44]
> /root/side-projects/test_install/mxnet/dmlc-core/include/dmlc/logging.h:235:
> [08:09:44] src/engine/./threaded_engine.h:306: [08:09:44]
> src/operator/./convolution-inl.h:279: Check failed: (param_.workspace) >=
> (required_size)
> Minimum workspace size: 1513881600 Bytes
> Given: 536870912 Bytes
> An fatal error occurred in asynchronous engine operation. If you do not
> know what caused this error, you can try set environment variable
> MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This
> will force all operations to be synchronous and backtrace will give you the
> series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE
> back to empty after debugging.
> terminate called after throwing an instance of 'dmlc::Error'
> what(): [08:09:44] src/engine/./threaded_engine.h:306: [08:09:44]
> src/operator/./convolution-inl.h:279: Check failed: (param_.workspace) >=
> (required_size)
> Minimum workspace size: 1513881600 Bytes
> Given: 536870912 Bytes
> An fatal error occurred in asynchronous engine operation. If you do not
> know what caused this error, you can try set environment variable
> MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This
> will force all operations to be synchronous and backtrace will give you the
> series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE
> back to empty after debugging.
> Aborted
>
> I tried increasing the workspace in the model_vgg19 file to 2048, however
> this didn't help. Any ideas? Is it possible to use cudnn to get around this
> problem? How can I run the modell with cudnn?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2501#issuecomment-228523170>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13mDCgXsSXs2SfmYb6yDZFGRoTdjNks5qPOYYgaJpZM4I7c2I>
> .
>
-- 
Sent from mobile phone

**Comment by randomrandom** [comment]
I also thought it might be because of the input, though I believe I'm currently using 640x480. What size would you recommend?

**Comment by VinniaKemala** [comment]
I try to run boost_train.py, still get error like this:

Traceback (most recent call last):
  File "D:\UI MAGISTER FASILKOM\KULIAH\MXNET\mxnet-master-20161013\example\neural-style\end_to_end\boost_train.py", line 51, in <module>
    gens = [gen_v4.get_module("g0", dshape, ctx),
  File "D:\UI MAGISTER FASILKOM\KULIAH\MXNET\mxnet-master-20161013\example\neural-style\end_to_end\gen_v4.py", line 82, in get_module
    mod.init_params(initializer=mx.init.Xavier(magnitude=2.))
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\module.py", line 190, in init_params
    _impl(name, arr, arg_params)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\module\module.py", line 187, in _impl
    initializer(name, arr)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\initializer.py", line 44, in __call__
    self._init_weight(name, arr)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\initializer.py", line 266, in _init_weight
    random.uniform(-scale, scale, out=arr)
  File "C:\Python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\random.py", line 42, in uniform
    return _internal._sample_uniform(low=low, high=high, shape=out.shape, out=out)
AttributeError: 'module' object has no attribute '_sample_uniform'

 I'm new to mxnet, so I'm not sure how to fix it. Any ideas?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
