### ISSUE TITLE
Master test failing

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#3419]
@javelinjs @pluskid @tqchen @thirdwing Scala Julia and R tests are failing in master. Could you guys look into it?

**Comment by pluskid** [comment]
The last failure on master seems only due to a 404 not found error while attempting to download inception from R test? https://travis-ci.org/dmlc/mxnet/builds/163794009

**Comment by piiswrong** [comment]
@mli I thought we fixed data.dmlc.ml yesterday?

**Comment by mli** [comment]
should be fixed now

**Comment by thirdwing** [comment]
I think http://data.dmlc.ml/ is still not available.
I can disable that test for now

**Comment by mli** [comment]
it works well on my laptop. try it again or try data.mxnet.io?

**Comment by thirdwing** [comment]
404 error https://travis-ci.org/dmlc/mxnet/jobs/163868765#L2574

**Comment by mli** [comment]
copied all data in the original data/ directory.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
