### ISSUE TITLE
speech demo for decoding with kaldi

### ISSUE THREAD

**Issue by nichongjia** [apache/incubator-mxnet#3810]
After I trained the lstm model using speech_demo in mxnet, I want to decode for eval data.
But it occurs an error. The following is the one of the log file for decoding.
```
-------------------------------------------------------------------------------------------------------------------

# OMP_NUM_THREADS=1 python decode_mxnet.py --config ami_local_bptt.cfg --data_test exp_mxnet/data-for-mxnet/test.feats --data_label_mean exp_mxnet/data-for-mxnet/label_mean.feats --train_method simple --train_prefix ami --train_context cpu0 --train_batch_size 1 --data_test data_ihm-fmllr-tri4/ihm/eval/split20/1/mxnetInput.scp | latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=exp_kaldi/ihm/tri4a/graph_ami_fsh.o3g.kn.pr1-7/words.txt exp_mxnet/final.mdl exp_kaldi/ihm/tri4a/graph_ami_fsh.o3g.kn.pr1-7/HCLG.fst ark:- "ark:|gzip -c > exp_mxnet/decode_eval/lat.1.gz" 
# Started at Sat Nov 12 20:57:16 SGT 2016
#
latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=exp_kaldi/ihm/tri4a/graph_ami_fsh.o3g.kn.pr1-7/words.txt exp_mxnet/final.mdl exp_kaldi/ihm/tri4a/graph_ami_fsh.o3g.kn.pr1-7/HCLG.fst ark:- 'ark:|gzip -c > exp_mxnet/decode_eval/lat.1.gz' 
!! CMDLine overwriting data.test:
    'exp_mxnet/data-for-mxnet/test.feats' => 'data_ihm-fmllr-tri4/ihm/eval/split20/1/mxnetInput.scp'
!! CMDLine overwriting data.label_mean:
    'exp_mxnet/data-for-mxnet/label_mean.feats' => 'exp_mxnet/data-for-mxnet/label_mean.feats'
!! CMDLine overwriting train.batch_size:
    '40' => '1'
!! CMDLine overwriting train.context:
    'gpu0' => 'cpu0'
!! CMDLine overwriting train.method:
    'truncated-bptt' => 'simple'
!! CMDLine overwriting train.prefix:
    'ami' => 'ami'
================================================================================
[data]
kaldi_root = /home/nichongjia/Work/ASR/Tools/20150325kaldi-dyn
train = exp_mxnet/data-for-mxnet/train.feats
dev = exp_mxnet/data-for-mxnet/dev.feats
test = data_ihm-fmllr-tri4/ihm/eval/split20/1/mxnetInput.scp
out_file = exp_mxnet/data-for-mxnet/out_file.ark
format = kaldi
xdim = 40
ydim = 3991
label_mean = exp_mxnet/data-for-mxnet/label_mean.feats

[arch]
num_hidden = 1024
num_hidden_proj = 512
num_lstm_layer = 3

[train]
batch_size = 1
buckets = 100, 200, 300, 400, 500, 600, 700, 800
num_epoch = 12
truncate_len = 20
context = cpu0
method = simple
prefix = ami
learning_rate = 1
decay_factor = 2
decay_lower_bound = 1e-6
optimizer = speechSGD
momentum = 0.9
clip_gradient = 0
initializer = Uniform
init_scale = 0.05
weight_decay = 0.008
show_every = 1000

Loading data...
Summary of dataset ==================
bucket of len   9 : 2 samples
bucket of len  10 : 1 samples
bucket of len  11 : 3 samples
bucket of len  12 : 3 samples
bucket of len  13 : 8 samples
bucket of len  14 : 10 samples
bucket of len  15 : 5 samples
bucket of len  16 : 5 samples
bucket of len  17 : 7 samples
bucket of len  18 : 9 samples
bucket of len  19 : 3 samples
bucket of len  20 : 7 samples
bucket of len  21 : 9 samples
bucket of len  22 : 16 samples
bucket of len  23 : 6 samples
bucket of len  24 : 7 samples
bucket of len  25 : 13 samples
bucket of len  26 : 13 samples
bucket of len  27 : 13 samples
bucket of len  28 : 12 samples
bucket of len  29 : 4 samples
bucket of len  30 : 13 samples
bucket of len  31 : 11 samples
bucket of len  32 : 9 samples
bucket of len  33 : 6 samples
bucket of len  34 : 7 samples
bucket of len  35 : 7 samples
bucket of len  36 : 4 samples
bucket of len  37 : 5 samples
bucket of len  38 : 8 samples
bucket of len  39 : 3 samples
bucket of len  40 : 5 samples
bucket of len  41 : 9 samples
bucket of len  42 : 7 samples
bucket of len  43 : 4 samples
bucket of len  44 : 8 samples
bucket of len  45 : 4 samples
bucket of len  46 : 5 samples
bucket of len  47 : 3 samples
bucket of len  48 : 2 samples
bucket of len  49 : 3 samples
bucket of len  50 : 5 samples
bucket of len  51 : 3 samples
bucket of len  52 : 4 samples
bucket of len  53 : 6 samples
bucket of len  54 : 3 samples
bucket of len  55 : 4 samples
bucket of len  56 : 6 samples
bucket of len  57 : 2 samples
bucket of len  58 : 8 samples
bucket of len  59 : 5 samples
bucket of len  60 : 3 samples
bucket of len  61 : 4 samples
bucket of len  62 : 2 samples
bucket of len  63 : 5 samples
bucket of len  64 : 3 samples
bucket of len  65 : 5 samples
bucket of len  66 : 5 samples
bucket of len  67 : 5 samples
bucket of len  68 : 4 samples
bucket of len  69 : 2 samples
bucket of len  70 : 3 samples
bucket of len  71 : 2 samples
bucket of len  72 : 3 samples
bucket of len  73 : 2 samples
bucket of len  74 : 1 samples
bucket of len  75 : 9 samples
bucket of len  76 : 6 samples
bucket of len  77 : 4 samples
bucket of len  78 : 1 samples
bucket of len  79 : 3 samples
bucket of len  80 : 4 samples
bucket of len  81 : 6 samples
bucket of len  82 : 3 samples
bucket of len  83 : 6 samples
bucket of len  84 : 3 samples
bucket of len  85 : 5 samples
bucket of len  86 : 2 samples
bucket of len  87 : 5 samples
bucket of len  88 : 5 samples
bucket of len  89 : 2 samples
bucket of len  90 : 5 samples
bucket of len  91 : 3 samples
bucket of len  92 : 4 samples
bucket of len  93 : 4 samples
bucket of len  94 : 5 samples
bucket of len  95 : 2 samples
bucket of len  96 : 3 samples
bucket of len  97 : 3 samples
bucket of len  98 : 3 samples
bucket of len  99 : 7 samples
bucket of len 100 : 3 samples
bucket of len 101 : 3 samples
bucket of len 102 : 2 samples
bucket of len 103 : 7 samples
bucket of len 104 : 1 samples
bucket of len 105 : 1 samples
bucket of len 106 : 2 samples
bucket of len 107 : 2 samples
bucket of len 108 : 5 samples
bucket of len 109 : 2 samples
bucket of len 110 : 3 samples
bucket of len 111 : 1 samples
bucket of len 112 : 2 samples
bucket of len 113 : 3 samples
bucket of len 114 : 3 samples
bucket of len 115 : 3 samples
bucket of len 116 : 5 samples
bucket of len 117 : 5 samples
bucket of len 118 : 3 samples
bucket of len 119 : 4 samples
bucket of len 120 : 2 samples
bucket of len 121 : 2 samples
bucket of len 122 : 1 samples
bucket of len 123 : 2 samples
bucket of len 124 : 4 samples
bucket of len 125 : 4 samples
bucket of len 127 : 2 samples
bucket of len 128 : 4 samples
bucket of len 129 : 4 samples
bucket of len 130 : 2 samples
bucket of len 131 : 4 samples
bucket of len 132 : 4 samples
bucket of len 133 : 5 samples
bucket of len 134 : 4 samples
bucket of len 135 : 6 samples
bucket of len 136 : 3 samples
bucket of len 137 : 2 samples
bucket of len 138 : 2 samples
bucket of len 139 : 2 samples
bucket of len 140 : 4 samples
bucket of len 141 : 3 samples
bucket of len 142 : 3 samples
bucket of len 143 : 4 samples
bucket of len 144 : 2 samples
bucket of len 145 : 4 samples
bucket of len 146 : 2 samples
bucket of len 147 : 1 samples
bucket of len 148 : 2 samples
bucket of len 149 : 2 samples
bucket of len 150 : 1 samples
bucket of len 151 : 9 samples
bucket of len 152 : 3 samples
bucket of len 154 : 3 samples
bucket of len 155 : 1 samples
bucket of len 156 : 5 samples
bucket of len 157 : 2 samples
bucket of len 158 : 1 samples
bucket of len 159 : 1 samples
bucket of len 160 : 1 samples
bucket of len 161 : 1 samples
bucket of len 162 : 2 samples
bucket of len 163 : 1 samples
bucket of len 164 : 3 samples
bucket of len 165 : 1 samples
bucket of len 166 : 2 samples
bucket of len 168 : 2 samples
bucket of len 169 : 1 samples
bucket of len 170 : 3 samples
bucket of len 171 : 1 samples
bucket of len 172 : 1 samples
bucket of len 173 : 2 samples
bucket of len 174 : 4 samples
bucket of len 175 : 2 samples
bucket of len 176 : 3 samples
bucket of len 177 : 1 samples
bucket of len 178 : 1 samples
bucket of len 179 : 1 samples
bucket of len 180 : 2 samples
bucket of len 181 : 1 samples
bucket of len 182 : 1 samples
bucket of len 183 : 3 samples
bucket of len 184 : 1 samples
bucket of len 185 : 5 samples
bucket of len 186 : 1 samples
bucket of len 188 : 1 samples
bucket of len 190 : 3 samples
bucket of len 191 : 1 samples
bucket of len 192 : 2 samples
bucket of len 193 : 3 samples
bucket of len 194 : 2 samples
bucket of len 195 : 3 samples
bucket of len 197 : 1 samples
bucket of len 200 : 2 samples
bucket of len 201 : 1 samples
bucket of len 202 : 2 samples
bucket of len 203 : 2 samples
bucket of len 204 : 3 samples
bucket of len 205 : 3 samples
bucket of len 206 : 3 samples
bucket of len 208 : 3 samples
bucket of len 209 : 1 samples
bucket of len 210 : 3 samples
bucket of len 211 : 4 samples
bucket of len 212 : 2 samples
bucket of len 213 : 1 samples
bucket of len 216 : 2 samples
bucket of len 219 : 2 samples
bucket of len 220 : 1 samples
bucket of len 221 : 3 samples
bucket of len 222 : 2 samples
bucket of len 223 : 2 samples
bucket of len 225 : 4 samples
bucket of len 226 : 2 samples
bucket of len 227 : 1 samples
bucket of len 228 : 2 samples
bucket of len 229 : 2 samples
bucket of len 230 : 1 samples
bucket of len 232 : 1 samples
bucket of len 233 : 2 samples
bucket of len 234 : 1 samples
bucket of len 235 : 3 samples
bucket of len 236 : 2 samples
bucket of len 237 : 1 samples
bucket of len 238 : 2 samples
bucket of len 239 : 1 samples
bucket of len 240 : 2 samples
bucket of len 242 : 1 samples
bucket of len 245 : 1 samples
bucket of len 246 : 1 samples
bucket of len 247 : 1 samples
bucket of len 250 : 1 samples
bucket of len 251 : 1 samples
bucket of len 254 : 2 samples
bucket of len 255 : 3 samples
bucket of len 256 : 2 samples
bucket of len 257 : 1 samples
bucket of len 258 : 1 samples
bucket of len 259 : 3 samples
bucket of len 260 : 1 samples
bucket of len 262 : 1 samples
bucket of len 263 : 1 samples
bucket of len 264 : 4 samples
bucket of len 265 : 2 samples
bucket of len 266 : 3 samples
bucket of len 267 : 3 samples
bucket of len 268 : 2 samples
bucket of len 269 : 1 samples
bucket of len 270 : 2 samples
bucket of len 271 : 1 samples
bucket of len 273 : 2 samples
bucket of len 276 : 1 samples
bucket of len 277 : 2 samples
bucket of len 278 : 2 samples
bucket of len 279 : 1 samples
bucket of len 280 : 1 samples
bucket of len 281 : 3 samples
bucket of len 282 : 1 samples
bucket of len 283 : 1 samples
bucket of len 285 : 1 samples
bucket of len 286 : 2 samples
bucket of len 288 : 2 samples
bucket of len 290 : 2 samples
bucket of len 291 : 4 samples
bucket of len 293 : 5 samples
bucket of len 295 : 2 samples
bucket of len 298 : 1 samples
bucket of len 301 : 1 samples
bucket of len 304 : 1 samples
bucket of len 307 : 1 samples
bucket of len 310 : 2 samples
bucket of len 311 : 1 samples
bucket of len 312 : 2 samples
bucket of len 313 : 2 samples
bucket of len 314 : 3 samples
bucket of len 315 : 1 samples
bucket of len 320 : 1 samples
bucket of len 321 : 1 samples
bucket of len 322 : 1 samples
bucket of len 323 : 1 samples
bucket of len 325 : 1 samples
bucket of len 326 : 4 samples
bucket of len 331 : 1 samples
bucket of len 332 : 2 samples
bucket of len 334 : 2 samples
bucket of len 335 : 1 samples
bucket of len 336 : 1 samples
bucket of len 337 : 3 samples
bucket of len 340 : 2 samples
bucket of len 341 : 1 samples
bucket of len 342 : 1 samples
bucket of len 343 : 1 samples
bucket of len 344 : 1 samples
bucket of len 346 : 1 samples
bucket of len 347 : 1 samples
bucket of len 350 : 1 samples
bucket of len 352 : 2 samples
bucket of len 358 : 1 samples
bucket of len 360 : 2 samples
bucket of len 362 : 1 samples
bucket of len 363 : 1 samples
bucket of len 364 : 1 samples
bucket of len 365 : 2 samples
bucket of len 367 : 3 samples
bucket of len 368 : 1 samples
bucket of len 369 : 1 samples
bucket of len 370 : 2 samples
bucket of len 371 : 1 samples
bucket of len 372 : 1 samples
bucket of len 376 : 1 samples
bucket of len 379 : 3 samples
bucket of len 380 : 1 samples
bucket of len 381 : 1 samples
bucket of len 382 : 1 samples
bucket of len 385 : 1 samples
bucket of len 386 : 1 samples
bucket of len 388 : 2 samples
bucket of len 390 : 1 samples
bucket of len 392 : 1 samples
bucket of len 393 : 1 samples
bucket of len 395 : 1 samples
bucket of len 397 : 1 samples
bucket of len 398 : 4 samples
bucket of len 400 : 1 samples
bucket of len 401 : 1 samples
bucket of len 402 : 1 samples
bucket of len 404 : 3 samples
bucket of len 406 : 1 samples
bucket of len 407 : 1 samples
bucket of len 408 : 1 samples
bucket of len 409 : 1 samples
bucket of len 415 : 1 samples
bucket of len 416 : 3 samples
bucket of len 418 : 1 samples
bucket of len 419 : 1 samples
bucket of len 421 : 1 samples
bucket of len 422 : 1 samples
bucket of len 423 : 3 samples
bucket of len 424 : 1 samples
bucket of len 426 : 1 samples
bucket of len 433 : 1 samples
bucket of len 437 : 1 samples
bucket of len 438 : 1 samples
bucket of len 442 : 5 samples
bucket of len 445 : 1 samples
bucket of len 446 : 2 samples
bucket of len 447 : 1 samples
bucket of len 449 : 1 samples
bucket of len 450 : 2 samples
bucket of len 452 : 2 samples
bucket of len 455 : 1 samples
bucket of len 457 : 1 samples
bucket of len 458 : 2 samples
bucket of len 459 : 2 samples
bucket of len 462 : 1 samples
bucket of len 465 : 1 samples
bucket of len 466 : 2 samples
bucket of len 472 : 1 samples
bucket of len 473 : 2 samples
bucket of len 475 : 1 samples
bucket of len 480 : 1 samples
bucket of len 482 : 1 samples
bucket of len 486 : 1 samples
bucket of len 490 : 1 samples
bucket of len 493 : 2 samples
bucket of len 496 : 1 samples
bucket of len 498 : 1 samples
bucket of len 499 : 1 samples
bucket of len 500 : 1 samples
bucket of len 504 : 1 samples
bucket of len 512 : 1 samples
bucket of len 516 : 1 samples
bucket of len 520 : 2 samples
bucket of len 523 : 1 samples
bucket of len 526 : 1 samples
bucket of len 528 : 2 samples
bucket of len 529 : 2 samples
bucket of len 531 : 1 samples
bucket of len 533 : 1 samples
bucket of len 534 : 2 samples
bucket of len 536 : 1 samples
bucket of len 539 : 1 samples
bucket of len 544 : 2 samples
bucket of len 552 : 1 samples
bucket of len 553 : 1 samples
bucket of len 560 : 1 samples
bucket of len 566 : 1 samples
bucket of len 567 : 1 samples
bucket of len 569 : 1 samples
bucket of len 575 : 1 samples
bucket of len 579 : 1 samples
bucket of len 583 : 1 samples
bucket of len 585 : 1 samples
bucket of len 589 : 1 samples
bucket of len 599 : 1 samples
bucket of len 601 : 1 samples
bucket of len 603 : 1 samples
bucket of len 604 : 1 samples
bucket of len 615 : 1 samples
bucket of len 622 : 3 samples
bucket of len 625 : 1 samples
bucket of len 630 : 1 samples
bucket of len 638 : 1 samples
bucket of len 641 : 1 samples
bucket of len 645 : 1 samples
bucket of len 646 : 1 samples
bucket of len 651 : 1 samples
bucket of len 654 : 1 samples
bucket of len 656 : 2 samples
bucket of len 664 : 1 samples
bucket of len 666 : 1 samples
bucket of len 668 : 2 samples
bucket of len 669 : 1 samples
bucket of len 677 : 1 samples
bucket of len 684 : 1 samples
bucket of len 687 : 1 samples
bucket of len 698 : 1 samples
bucket of len 703 : 1 samples
bucket of len 708 : 1 samples
bucket of len 727 : 1 samples
bucket of len 729 : 1 samples
bucket of len 737 : 1 samples
bucket of len 740 : 1 samples
bucket of len 744 : 2 samples
bucket of len 746 : 1 samples
bucket of len 749 : 1 samples
bucket of len 750 : 1 samples
bucket of len 751 : 1 samples
bucket of len 765 : 1 samples
bucket of len 778 : 1 samples
bucket of len 786 : 1 samples
bucket of len 791 : 1 samples
bucket of len 799 : 1 samples
bucket of len 800 : 1 samples
bucket of len 806 : 1 samples
bucket of len 833 : 1 samples
bucket of len 874 : 1 samples
bucket of len 878 : 1 samples
bucket of len 882 : 1 samples
bucket of len 894 : 1 samples
bucket of len 947 : 1 samples
bucket of len 951 : 1 samples
bucket of len 991 : 1 samples
bucket of len 1022 : 1 samples
bucket of len 1028 : 1 samples
bucket of len 1044 : 1 samples
bucket of len 1054 : 1 samples
bucket of len 1269 : 1 samples
[20:57:20] src/operator/./reshape-inl.h:270: Using target_shape will be deprecated.
[20:57:21] src/operator/./reshape-inl.h:270: Using target_shape will be deprecated.
[20:57:21] src/operator/./reshape-inl.h:270: Using target_shape will be deprecated.
Traceback (most recent call last):
  File "decode_mxnet.py", line 134, in <module>
    for preds, i_batch, batch in module.iter_predict(data_test):
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 203, in iter_predict
    self.forward(eval_batch, is_train=False)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/bucketing_module.py", line 263, in forward
    data_batch.provide_label)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/bucketing_module.py", line 216, in switch_bucket
    force_rebind=False, shared_module=self._curr_module)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 265, in bind
    grad_req=grad_req)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 170, in __init__
    self.label_layouts = self.decide_slices(label_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 184, in decide_slices
    assert len(data_shapes) > 0
AssertionError
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:163) Time taken 10.3109s: real-time factor assuming 100 frames/sec is inf
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:166) Done 0 utterances, failed for 0
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:168) Overall log-likelihood per frame is -nan over 0 frames.
# Accounting: time=10 threads=1
# Ended (code 1) at Sat Nov 12 20:57:26 SGT 2016, elapsed time 10 seconds
```

**Comment by piiswrong** [comment]
@pluskid @antinucleon

**Comment by pluskid** [comment]
@yzhang87 does this error look familiar to you?

**Comment by yzhang87** [comment]
@pluskid no. It's more like some recent change broke it. I'll take a look.

**Comment by yzhang87** [comment]
@nichongjia It is because we began to start check the label_shape but for test we don't have the label. I'll submit a fix.

**Comment by nichongjia** [comment]
@yzhang87  Thanks a lot, Yu. Previously, I also meet the errors when training the acoustic model in function def CrossEntropy(labels, preds) in file train_lstm_proj.py due to the label dimension error, so I just add a line in the for loop for reducing 1.

for i in range(preds.shape[0]):
        label = labels[i]
        label = label - 1 ##### this is the added line
        #print label,preds[i][int(label)]
        if label > 0:
            loss += -np.log(max(1e-10, preds[i][int(label)]))
            num_inst += 1
    return loss , num_inst

**Comment by yzhang87** [comment]
@nichongjia I think the correct way was adding your label dimension. Label 0 is reserved for the padding frames (garbage frame).

**Comment by nichongjia** [comment]
@yzhang87 Thanks a lot, Yu. I will extend the dimension of the label.
Previously, I had thought it is the cross-entropy computation.
I have modified the ydim by adding 1 in the configure file, and will re-do the experiments.
Thanks.

**Comment by nichongjia** [comment]
@yzhang87 when I decode by using the default setting, the same issue is still there.

**Comment by yzhang87** [comment]
Did you update it to the latest version? https://github.com/dmlc/mxnet/pull/3865/commits/75c4ecd241abf8e0a660810a1a68a2d7c01f1b0a
This should fix it. If not, please let me know.

**Comment by nichongjia** [comment]
Yes, I have updated the latest version, and re-compiled and re-installed.
The problem is still there.
The following is the error.

Traceback (most recent call last):
  File "decode_mxnet.py", line 145, in <module>
    for preds, i_batch, batch in module.iter_predict(data_test):
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 216, in iter_predict
    self.forward(eval_batch, is_train=False)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/bucketing_module.py", line 263, in forward
    data_batch.provide_label)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/bucketing_module.py", line 216, in switch_bucket
    force_rebind=False, shared_module=self._curr_module)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 286, in bind
    grad_req=grad_req, input_types=input_types)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 187, in __init__
    self.label_layouts = self.decide_slices(label_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 201, in decide_slices
    assert len(data_shapes) > 0
AssertionError

**Comment by yzhang87** [comment]
I wasn't able to reproduce the bug. Is this branch you were using now? https://github.com/nichongjia/mxnet/tree/master/example/speech-demo

Could you print data_batch.provide_label? it should be a None.
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/bucketing_module.py", line 263, in forward
data_batch.provide_label)

**Comment by nichongjia** [comment]
@yzhang87 I print the value of  data_batch.provide_label, it is [], and is not None.
I do not know which place I can set the value to be None.
Could you help me list it?

**Comment by yzhang87** [comment]
can you check your io_util.py?

It has been set here:

[https://github.com/dmlc/mxnet/blob/master/example/speech-demo/io_util.py#L43](url)

**Comment by nichongjia** [comment]
Thanks a lot @yzhang87 ,
I will try it.

**Comment by yzhang87** [comment]
Please also change this line:
https://github.com/yzhang87/mxnet/blob/master/example/speech-demo/decode_mxnet.py#L145
(Add [0] after batch.utt_len)

This appears to be an issue with the latest version of Numpy. It is an error to treat a single-element array as a scalar for the purposes of indexing now.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
