### ISSUE TITLE
Why monitor can't print ".*backward.*" statistics when using BucketingModule?

### ISSUE THREAD

**Issue by moveforever** [apache/incubator-mxnet#5644]
when i use BucketingModule, i came across a problem that it doesnot print backward weight or data.
code is as followed:
```
    mod = mx.mod.BucketingModule(sym_gen,
                                 default_bucket_key=train.default_bucket_key,
                                 context=devs)

    mon = mx.mon.Monitor(
        500,                 # Print every 100 batches\n",
        norm_stat)         # The statistics function defined above\n",

  # start train
    print "start training..."
    mod.fit(train, test, eval_metric=eval_metric,
          num_epoch = epoch_num,
          epoch_end_callback=epoch_end_callback,
          batch_end_callback=batch_end_callback,
          optimizer='adam', optimizer_params=optimizer_params,
          initializer=mx.init.Xavier(factor_type="in", magnitude=2),
          monitor=mon)


```
Any help will appreciate

**Comment by tornadomeet** [comment]
does `mx.mod.Module` do well in your code?

**Comment by moveforever** [comment]
yes, it can.

**Comment by moveforever** [comment]
i add two line in mxnet-0.9.4-py2.7.egg/mxnet/monitor.py as followed:
![t](https://cloud.githubusercontent.com/assets/5248288/24550504/ed62ae48-1650-11e7-9857-12b5c631af22.png)
i print all names of arg_param and aux_param, and there is not existed names about backward.
so i doubt it exist a problem or a bug in mx.mod.BucketingModule when using monitor printing.

**Comment by piiswrong** [comment]
fixed by https://github.com/dmlc/mxnet/pull/5752

**Comment by fhieber** [comment]
@piiswrong This problem apparently still exists in latest version of MXNet: pattern=".*" only prints weights/biases when using a BucketingModule, but everything if using a regular Module.

**Comment by piiswrong** [comment]
not sure why. I'll take a look later

**Comment by fhieber** [comment]
@piiswrong 
For reference, I am using a custom fit method with a monitor installed like this:
```python
# self.module is a BucketingModule
[...]
monitor = mx.monitor.Monitor(
  interval=50 stat_func=None, pattern=".*", sort=True)
self.module.install_monitor(monitor)
[...]
next_data_batch = train_iter.next()
while True:
  [...]
  batch = next_data_batch
  if monitor is not None:
    monitor.tic()
  self.module.forward_backward(batch)
  self.module.update()
  if train_iter.iter_next():
    # pre-fetch next batch
    next_data_batch = train_iter.next()
    self.module.prepare(next_data_batch)
  self.module.update_metric(metric_train, batch.label)
  monitor is not None:
    monitor.toc_print()
```

In fact, 'everything' (including backward arrays) is eventually printed, but not consistently after every 50 batches. My suspicion is that it only prints them 
- either when all submodules (in this case for different sequence lengths) are at least used once
- or only when the default bucket_key module is being used for a batch.

It would be great to have a consistent output printed for every x batches, regardless whether this is a default_bucket_key batch or not.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
