### ISSUE TITLE
gluon hang-up unexpectedly

### ISSUE THREAD

**Issue by shuokay** [apache/incubator-mxnet#8997]
```python
import mxnet as mx
def get_net():
    net = mx.gluon.model_zoo.vision.resnet50_v1(pretrained=False)
    net.initialize()
    net.collect_params().reset_ctx(mx.gpu(0))
    return net

if __name__ == "__main__":
    print get_net()
```
save the code to `tmp.py` and run it with `python tmp.py`, after printing the net, it hang-up unexceptedly.
if `export MXNET_ENGINE_TYPE=NaiveEngine`, test passed

**Comment by eric-haibin-lin** [comment]
If you add `mx.nd.waitall()` to the end, does it work? 

https://mxnet.incubator.apache.org/tutorials/basic/ndarray.html#lazy-evaluation-and-automatic-parallelization

**Comment by piiswrong** [comment]
@cjolivier01  looks like another shutdown problem?

**Comment by cjolivier01** [comment]
I will take a look

**Comment by shuokay** [comment]
@eric-haibin-lin @cjolivier01 

1. add `mx.nd.waitall()`, gluon exits normally.
2. without `mx.nd.waitwall()`, gluon doesn't exit or give the following error:
```
terminate called recursively 
terminate called after throwing an instance of 'dmlc::Error'
```

**Comment by cjolivier01** [comment]
Is there error or hang 100% of the time? If not, what’s the frequency?

**Comment by shuokay** [comment]
Test the code 10 times
`export MXNET_ENGINE_TYPE=NaiveEngine` (default) or `export MXNET_ENGINE_TYPE=ThreadedEngine`
exit normally:  10
hang up: 0
error: 0
`export MXNET_ENGINE_TYPE=ThreadedEnginePerDevice` (default)
exit normally:  4
hang up: 6
error: 0
So the hang up problem only occur when `MXNET_ENGINE_TYPE=ThreadedEnginePerDevice`

**Comment by cjolivier01** [comment]
What are your build Config? MKL? CUDA? Etc? I’m having trouble reproducing.

**Comment by shuokay** [comment]
config.mk: https://gist.github.com/shuokay/5e9d4af8b4c13daa82ce8e04f89a1db0

**Comment by ZiyueHuang** [comment]
I can also reproduce this error by `make -j  USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda`

**Comment by gautamkmr** [comment]
Please add the labels:  "Gluon", "Bug", "Thread safety"

**Comment by apeforest** [comment]
@cjolivier01 Hi Chris, are you still working on this issue? We have another [issue](https://github.com/apache/incubator-mxnet/issues/9167) which I believe can also be fixed by this.

**Comment by apeforest** [comment]
@shuokay I can no longer reproduce this issue. Please help to verify. Thanks

**Comment by sandeep-krishnamurthy** [comment]
Resolving as it is not reproducible. Please reopen if issue still persists.
