### ISSUE TITLE
(Flaky?) perl test failure 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9381]
I'm looking at the build status for each commit on MXNet master and noticed that perl test failed once a few weeks ago. Was this already fixed? @sergeykolychev 

```
Test Summary Report

-------------------

t/test_loss.t             (Wstat: 256 Tests: 24 Failed: 1)

  Failed test:  21

  Non-zero exit status: 1

Files=27, Tests=6721, 123 wallclock secs ( 0.77 usr  0.24 sys + 348.20 cusr 744.50 csys = 1093.71 CPU)

```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/74/pipeline

**Comment by marcoabreu** [comment]
#   Failed test at t/test_loss.t line 233.
# Looks like you failed 1 test of 24.

**Comment by sergeykolychev** [comment]
Was not aware of this, I'll fix this asap.

**Comment by sergeykolychev** [comment]
Should be fixed by https://github.com/apache/incubator-mxnet/pull/9414

**Comment by marcoabreu** [comment]
Hey @sergeykolychev , this is still occuring: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11358/19/pipeline/744

**Comment by sergeykolychev** [comment]
@marcoabreu I'll add static seed to these tests in the PR that I have open right now. Thanks.

**Comment by marcoabreu** [comment]
Would it be possible to track the issue down? Our experience showed that setting a fixed seed often masks an actual bug in our implementation. I'd appreciate it very much if you wouldn't mind :)

**Comment by sergeykolychev** [comment]
@marcoabreu I've take a look, but these particular tests do need a pre-set seed.
These tests are essentially a set of network trainings and expect a specific loss value for any random initialization is probably asking too much. I am fairly sure there's no bug in perl implementation that causes this.

**Comment by marcoabreu** [comment]
ok, thanks for looking into it!

**Comment by lupesko** [comment]
@sergeykolychev thanks for the explanation. Would be great if you can follow up with the static seed to ensure the test is not flaky. Thanks!

**Comment by lanking520** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-13819/4/pipeline/235/
Add one datapoint

**Comment by ChaiBapchya** [comment]
Another data point - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15953/7/pipeline/

**Comment by sergeykolychev** [comment]
@ChaiBapchya Thank you for the report, I'll take a look.
